import fs from 'node:fs';
import solc from 'solc';
const name = 'ProoflineCredential';
const input = {
  language: 'Solidity',
  sources: {
    [`${name}.sol`]: {
      content: fs.readFileSync(`contracts/src/${name}.sol`, 'utf8'),
    },
  },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    evmVersion: 'cancun',
    outputSelection: {
      '*': {
        '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object'],
      },
    },
  },
};
const output = JSON.parse(
  solc.compile(JSON.stringify(input), {
    import: (path) => {
      try {
        const contents = fs.readFileSync(`node_modules/${path}`, 'utf8');
        input.sources[path] = { content: contents };
        return { contents };
      } catch {
        return { error: `Missing import ${path}` };
      }
    },
  }),
);
for (const error of output.errors || []) console.error(error.formattedMessage);
if (output.errors?.some((e) => e.severity === 'error')) process.exit(1);
const contract = output.contracts[`${name}.sol`][name];
fs.mkdirSync('lib/generated', { recursive: true });
fs.mkdirSync('contracts/out', { recursive: true });
fs.writeFileSync(
  'lib/generated/abi.ts',
  `// Generated by npm run compile:contract.\nexport const credentialAbi = ${JSON.stringify(contract.abi, null, 2)} as const;\n`,
);
fs.writeFileSync(
  'contracts/out/ProoflineCredential.json',
  JSON.stringify(contract, null, 2),
);
fs.writeFileSync(
  'contracts/out/standard-input.json',
  JSON.stringify(input, null, 2),
);
console.log(
  `Compiled ${name} with ${solc.version()}; runtime ${contract.evm.deployedBytecode.object.length / 2} bytes.`,
);
